### ISSUE TITLE
filters on annotations queries, some fields works, others not

### ISSUE THREAD

**Issue by 0gust1** [rcsb/rcsb-api-tools#2] opened 2022-01-19 16:40 UTC
Hi,

We have a strange behavior with the filters on the annotation query.
We want to filter the on some feature types, for some it works for others not.
Some annotation types (here `MUTATION`) seems to be invisible to the filter. It also seems it does not depend on the filter operation.

You'll find below example requests

Do you have an idea of what's going on ?
(We may have overlooked some thing, if so, let us know).

### OK case - all annotations

```
{
  annotations(reference: UNIPROT, queryId: "P01584", sources: [PDB_ENTITY, PDB_INSTANCE, UNIPROT]) {
    source
    features {
      feature_id
      description
      feature_positions {
        beg_ori_id
        beg_seq_id
        value
        values
        end_ori_id
        end_seq_id
        open_begin
        open_end
      }
      provenance_source
      name
      type
      value
    }
    target_id
  }
}
```

=> **In the response we get some mutation feature**s

### OK case - filter on unobserved_residues and conflicts

```
{
  annotations(reference: UNIPROT, queryId: "P01584", sources: [PDB_INSTANCE, PDB_ENTITY, UNIPROT], filters: [{operation: contains, field: type, values: ["UNOBSERVED_", "CONFLICT"]}]) {
    source
    features {
      feature_id
      description
      feature_positions {
        beg_ori_id
        beg_seq_id
        value
        values
        end_ori_id
        end_seq_id
        open_begin
        open_end
      }
      provenance_source
      name
      type
      value
    }
    target_id
  }
}
```
=> everything seems ok

### NOK case - filter on mutations

```
{
  annotations(reference: UNIPROT, queryId: "P01584", sources: [PDB_INSTANCE, PDB_ENTITY, UNIPROT], 
    filters: [{operation: contains, field: type, values: ["MUTATION"]}]) {
    source
    features {
      feature_id
      description
      feature_positions {
        beg_ori_id
        beg_seq_id
        value
        values
        end_ori_id
        end_seq_id
        open_begin
        open_end
      }
      provenance_source
      name
      type
      value
    }
    target_id
  }
}
```

=> here we get an empty response
```
{
  "data": {
    "annotations": []
  }
}
```

**Comment by bioinsilico** [comment] 2022-01-19 23:26
Thank you for reporting this bug. In short, the problem was related to case sensitive and how graphql-java enumerated values are handled (more info https://github.com/graphql-java-kickstart/graphql-java-tools/discussions/426). Now the graphql server should be fixed and the request should return the expected results. Please, let me know if you find any unexpected behavior.

**Comment by 0gust1** [comment] 2022-01-20 08:20
Just tested on the specific case above and it works as expected now. Thanks for the explanation, and hats off to the team for the reactivity !

**Closed as completed** 2022-01-27 15:52 UTC
Labels: bug
